import { NgModule, APP_INITIALIZER } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule } from '@angular/common/http';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { RouterModule, Routes } from '@angular/router';
import 'hammerjs';
import { SharedModule } from './core/modules/shared.module';
import { AppComponent } from './app.component';
import { FuseMainModule } from './main/main.module';
import { FuseSplashScreenService } from './core/services/splash-screen.service';
import { FuseConfigService } from './core/services/config.service';
import { FuseNavigationService } from './core/components/navigation/navigation.service';
import { TranslateModule } from '@ngx-translate/core';
import { keycloakInitializer } from './auth/keycloakInitializer';
import { KeycloakService, KeycloakAngularModule } from 'keycloak-angular';
import { AppAuthGuard } from './auth/appAuthGuard.service';
import { ApolloModule, Apollo } from 'apollo-angular';
import { HttpLinkModule, HttpLink } from 'apollo-angular-link-http';
import { CustomMatPaginatorIntl } from './core/custom-mat-paginator-intl/custom-mat-paginator-intl';
import { GatewayService } from './api/gateway.service';
import { ServiceWorkerModule } from '@angular/service-worker';
import { MatPaginatorIntl } from '@angular/material';
import { environment } from '../environments/environment';

/* do not edit the line below: autogenerated code */
const appRoutes: Routes = [
    {
        "path": "business-management",
        "loadChildren": "./main/content/business-management/business-management.module#BusinessManagementModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "PLATFORM-ADMIN"
            ]
        }
    },
    {
        "path": "profile",
        "loadChildren": "./main/content/profile/profile.module#ProfileModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {}
    },
    {
        "path": "integrated-operating-environment",
        "loadChildren": "./main/content/integrated-operating-environment/integrated-operating-environment.module#IntegratedOperatingEnvironmentModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "OPERATOR",
                "OPERATION-SUPERVISOR",
                "BUSINESS-OWNER",
                "PLATFORM-ADMIN"
            ]
        }
    },
    {
        "path": "pos",
        "loadChildren": "./main/content/pos/pos.module#PosModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "developer",
                "PLATFORM-ADMIN",
                "BUSINESS-OWNER",
                "POS"
            ]
        }
    },
    {
        "path": "service",
        "loadChildren": "./main/content/service/service.module#ServiceModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "PLATFORM-ADMIN",
                "BUSINESS-OWNER",
                "BUSINESS-ADMIN",
                "SATELLITE",
                "OPERATOR",
                "OPERATION-SUPERVISOR"
            ]
        }
    },
    {
        "path": "client",
        "loadChildren": "./main/content/client/client.module#ClientModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "PLATFORM-ADMIN",
                "BUSINESS-OWNER",
                "OPERATION-SUPERVISOR"
            ]
        }
    },
    {
        "path": "driver-vehicle-assignment",
        "loadChildren": "./main/content/driver-vehicle-assignment/driver-vehicle-assignment.module#DriverVehicleAssignmentModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "PLATFORM-ADMIN",
                "BUSINESS-OWNER",
                "BUSINESS-ADMIN",
                "COORDINATOR",
                "OPERATION-SUPERVISOR"
            ]
        }
    },
    {
        "path": "subscriptions-recharges-report",
        "loadChildren": "./main/content/subscriptions-recharges-report/subscriptions-recharges-report.module#SubscriptionsRechargesReportModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "developer",
                "PLATFORM-ADMIN",
                "BUSINESS-OWNER"
            ]
        }
    },
    {
        "path": "vehicle",
        "loadChildren": "./main/content/vehicle/vehicle.module#VehicleModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "PLATFORM-ADMIN",
                "BUSINESS-OWNER",
                "COORDINATOR",
                "OPERATION-SUPERVISOR"
            ]
        }
    },
    {
        "path": "shifts",
        "loadChildren": "./main/content/shifts/shifts.module#ShiftsModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "PLATFORM-ADMIN",
                "BUSINESS-OWNER",
                "BUSINESS-ADMIN",
                "BUSINESS-VIEWER",
                "OPERATOR",
                "OPERATION-SUPERVISOR"
            ]
        }
    },
    {
        "path": "cronjob",
        "loadChildren": "./main/content/cronjob/cronjob.module#CronjobModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "SYSADMIN"
            ]
        }
    },
    {
        "path": "wallet-errors",
        "loadChildren": "./main/content/wallet/wallet.module#WalletModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "SYSADMIN_"
            ]
        }
    },
    {
        "path": "driver",
        "loadChildren": "./main/content/driver/driver.module#DriverModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "PLATFORM-ADMIN",
                "BUSINESS-OWNER",
                "COORDINATOR",
                "OPERATION-SUPERVISOR",
                "DISCIPLINARY-COMMITTEE"
            ]
        }
    },
    {
        "path": "wallet",
        "loadChildren": "./main/content/wallet/wallet.module#WalletModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "PLATFORM-ADMIN",
                "BUSINESS-OWNER",
                "DRIVER",
                "CLIENT",
                "BUSINESS-VIEWER",
                "OPERATOR"
            ]
        }
    },
    {
        "path": "poi",
        "loadChildren": "./main/content/integrated-operating-environment/integrated-operating-environment.module#IntegratedOperatingEnvironmentModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "OPERATOR",
                "OPERATION-SUPERVISOR",
                "BUSINESS-OWNER",
                "PLATFORM-ADMIN",
                "POI"
            ]
        }
    },
    {
        "path": "wallet-spending-rules",
        "loadChildren": "./main/content/wallet-spending-rules/wallet-spending-rules.module#WalletSpengingRulesModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "SYSADMIN_"
            ]
        }
    },
    {
        "path": "user-management",
        "loadChildren": "./main/content/user-management/user-management.module#UserManagementModule",
        "canActivate": [
            AppAuthGuard
        ],
        "data": {
            "roles": [
                "PLATFORM-ADMIN",
                "BUSINESS-OWNER"
            ]
        }
    },
    {
        "path": "**",
        "redirectTo": "profile"
    }
];

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    HttpClientModule,
    BrowserAnimationsModule,
    RouterModule.forRoot(appRoutes),
    SharedModule,
    TranslateModule.forRoot(),
    FuseMainModule,
    KeycloakAngularModule,
    ApolloModule,
    HttpLinkModule,
    ServiceWorkerModule.register('/emi/ngsw-worker.js', { enabled: environment.production }),
  ],
  providers: [
    {
      provide: MatPaginatorIntl,
      useClass: CustomMatPaginatorIntl
    },
    FuseSplashScreenService,
    FuseConfigService,
    FuseNavigationService,
    AppAuthGuard,
    {
      provide: APP_INITIALIZER,
      useFactory: keycloakInitializer,
      multi: true,
      deps: [KeycloakService]
    },
    GatewayService,
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
