import { FuseNavigationModelInterface } from '../core/components/navigation/navigation.model';

export class FuseNavigationModel implements FuseNavigationModelInterface {
    public model: any[];

    constructor() {
        /* do not edit the line below: autogenerated code */
        this.model = [
        {
                "id": "profile",
                "title": "profile",
                "translate": "NAV.profile",
                "type": "item",
                "url": "/profile",
                "icon": "account_circle",
                "priority": 100000
        },
        {
                "id": "POS",
                "title": "POS",
                "translate": "NAV.POS.self",
                "type": "group",
                "icon": "location_searching",
                "children": [
                        {
                                "id": "posPayments",
                                "title": "posPayments",
                                "translate": "NAV.POS.posPayments",
                                "type": "item",
                                "url": "/pos/payments",
                                "icon": "dashboard",
                                "priority": 1000,
                                "roles": [
                                        "developer",
                                        "PLATFORM-ADMIN",
                                        "BUSINESS-OWNER",
                                        "POS"
                                ]
                        },
                        {
                                "id": "withdrawal",
                                "title": "withdrawal",
                                "translate": "NAV.POS.withdrawal",
                                "type": "item",
                                "url": "/pos/withdrawal",
                                "icon": "dashboard",
                                "priority": 1000,
                                "roles": [
                                        "developer",
                                        "PLATFORM-ADMIN",
                                        "BUSINESS-OWNER",
                                        "POS"
                                ]
                        }
                ],
                "priority": 1000
        },
        {
                "id": "integrated-operating-environment",
                "title": "integrated-operating-environment",
                "translate": "NAV.integrated-operating-environment.self",
                "type": "group",
                "icon": "location_searching",
                "children": [
                        {
                                "id": "operation",
                                "title": "operation",
                                "translate": "NAV.integrated-operating-environment.operation",
                                "type": "item",
                                "url": "/service",
                                "icon": "explore",
                                "priority": 1000,
                                "roles": [
                                        "PLATFORM-ADMIN",
                                        "BUSINESS-OWNER",
                                        "BUSINESS-ADMIN",
                                        "SATELLITE",
                                        "OPERATOR",
                                        "OPERATION-SUPERVISOR"
                                ]
                        },
                        {
                                "id": "shifts",
                                "title": "shifts",
                                "translate": "NAV.integrated-operating-environment.shifts",
                                "type": "item",
                                "url": "/shifts",
                                "icon": "ballot",
                                "priority": 1000,
                                "roles": [
                                        "PLATFORM-ADMIN",
                                        "BUSINESS-OWNER",
                                        "BUSINESS-ADMIN",
                                        "BUSINESS-VIEWER",
                                        "OPERATOR",
                                        "OPERATION-SUPERVISOR"
                                ]
                        },
                        {
                                "id": "operator-workstation",
                                "title": "operator-workstation",
                                "translate": "NAV.integrated-operating-environment.operator-workstation",
                                "type": "item",
                                "url": "/poi",
                                "icon": "ballot",
                                "priority": 1000,
                                "roles": [
                                        "OPERATOR",
                                        "OPERATION-SUPERVISOR",
                                        "BUSINESS-OWNER",
                                        "PLATFORM-ADMIN",
                                        "POI"
                                ]
                        },
                        {
                                "id": "gods-eye",
                                "title": "gods-eye",
                                "translate": "NAV.integrated-operating-environment.gods-eye",
                                "type": "item",
                                "url": "/integrated-operating-environment/gods-eye",
                                "icon": "visibility",
                                "priority": 900,
                                "roles": [
                                        "OPERATOR",
                                        "OPERATION-SUPERVISOR",
                                        "BUSINESS-OWNER",
                                        "PLATFORM-ADMIN"
                                ]
                        }
                ],
                "priority": 1000
        },
        {
                "id": "REPORTS",
                "title": "REPORTS",
                "translate": "NAV.REPORTS.self",
                "type": "group",
                "icon": "location_searching",
                "children": [
                        {
                                "id": "subscriptions-recharges-report",
                                "title": "subscriptions-recharges-report",
                                "translate": "NAV.REPORTS.subscriptions-recharges-report",
                                "type": "item",
                                "url": "/subscriptions-recharges-report",
                                "icon": "rowing",
                                "priority": 1000,
                                "roles": [
                                        "developer",
                                        "PLATFORM-ADMIN",
                                        "BUSINESS-OWNER"
                                ]
                        }
                ],
                "priority": 500
        },
        {
                "id": "BUSINESS_UNIT_MANAGER",
                "title": "BUSINESS_UNIT_MANAGER",
                "translate": "NAV.BUSINESS_UNIT_MANAGER.self",
                "type": "group",
                "icon": "location_searching",
                "children": [
                        {
                                "id": "management",
                                "title": "management",
                                "translate": "NAV.BUSINESS_UNIT_MANAGER.management.self",
                                "type": "collapse",
                                "icon": "settings",
                                "children": [
                                        {
                                                "id": "business-management",
                                                "title": "business-management",
                                                "translate": "NAV.BUSINESS_UNIT_MANAGER.management.business-management",
                                                "type": "item",
                                                "url": "/business-management",
                                                "icon": "business",
                                                "priority": 3000,
                                                "roles": [
                                                        "PLATFORM-ADMIN"
                                                ]
                                        },
                                        {
                                                "id": "user-management",
                                                "title": "user-management",
                                                "translate": "NAV.BUSINESS_UNIT_MANAGER.management.user-management",
                                                "type": "item",
                                                "url": "/user-management",
                                                "icon": "face",
                                                "priority": 2000,
                                                "roles": [
                                                        "PLATFORM-ADMIN",
                                                        "BUSINESS-OWNER"
                                                ]
                                        },
                                        {
                                                "id": "client",
                                                "title": "client",
                                                "translate": "NAV.BUSINESS_UNIT_MANAGER.management.client",
                                                "type": "item",
                                                "url": "/client",
                                                "icon": "dashboard",
                                                "priority": 1000,
                                                "roles": [
                                                        "PLATFORM-ADMIN",
                                                        "BUSINESS-OWNER",
                                                        "OPERATION-SUPERVISOR"
                                                ]
                                        },
                                        {
                                                "id": "driver-management",
                                                "title": "driver-management",
                                                "translate": "NAV.BUSINESS_UNIT_MANAGER.management.driver-management",
                                                "type": "item",
                                                "url": "/driver",
                                                "icon": "airline_seat_recline_normal",
                                                "priority": 1000,
                                                "roles": [
                                                        "PLATFORM-ADMIN",
                                                        "BUSINESS-OWNER",
                                                        "COORDINATOR",
                                                        "OPERATION-SUPERVISOR",
                                                        "DISCIPLINARY-COMMITTEE"
                                                ]
                                        },
                                        {
                                                "id": "vehicle",
                                                "title": "vehicle",
                                                "translate": "NAV.BUSINESS_UNIT_MANAGER.management.vehicle",
                                                "type": "item",
                                                "url": "/vehicle",
                                                "icon": "directions_bus",
                                                "priority": 1000,
                                                "roles": [
                                                        "PLATFORM-ADMIN",
                                                        "BUSINESS-OWNER",
                                                        "COORDINATOR",
                                                        "OPERATION-SUPERVISOR"
                                                ]
                                        },
                                        {
                                                "id": "driver-vehicle-assignment",
                                                "title": "driver-vehicle-assignment",
                                                "translate": "NAV.BUSINESS_UNIT_MANAGER.management.driver-vehicle-assignment",
                                                "type": "item",
                                                "url": "/driver-vehicle-assignment",
                                                "icon": "assignment",
                                                "priority": 900,
                                                "roles": [
                                                        "PLATFORM-ADMIN",
                                                        "BUSINESS-OWNER",
                                                        "BUSINESS-ADMIN",
                                                        "COORDINATOR",
                                                        "OPERATION-SUPERVISOR"
                                                ]
                                        }
                                ],
                                "priority": 2000
                        },
                        {
                                "id": "WALLET",
                                "title": "WALLET",
                                "translate": "NAV.BUSINESS_UNIT_MANAGER.WALLET.self",
                                "type": "collapse",
                                "icon": "account_balance_wallet",
                                "children": [
                                        {
                                                "id": "historical-transaction-wallet",
                                                "title": "historical-transaction-wallet",
                                                "translate": "NAV.BUSINESS_UNIT_MANAGER.WALLET.historical-transaction-wallet",
                                                "type": "item",
                                                "url": "/wallet/transaction-history",
                                                "icon": "history",
                                                "priority": 4000,
                                                "roles": [
                                                        "PLATFORM-ADMIN",
                                                        "BUSINESS-OWNER",
                                                        "DRIVER",
                                                        "CLIENT",
                                                        "BUSINESS-VIEWER",
                                                        "OPERATOR"
                                                ]
                                        },
                                        {
                                                "id": "manual-wallet-adjustments",
                                                "title": "manual-wallet-adjustments",
                                                "translate": "NAV.BUSINESS_UNIT_MANAGER.WALLET.manual-wallet-adjustments",
                                                "type": "item",
                                                "url": "/wallet/manual-pocket-adjustment",
                                                "icon": "adjust",
                                                "priority": 3000,
                                                "roles": [
                                                        "PLATFORM-ADMIN",
                                                        "BUSINESS-OWNER",
                                                        "BUSINESS-ADMIN"
                                                ]
                                        },
                                        {
                                                "id": "wallet-spending-rules",
                                                "title": "wallet-spending-rules",
                                                "translate": "NAV.BUSINESS_UNIT_MANAGER.WALLET.wallet-spending-rules",
                                                "type": "item",
                                                "url": "/wallet-spending-rules",
                                                "icon": "dashboard",
                                                "priority": 2000,
                                                "roles": [
                                                        "SYSADMIN_"
                                                ]
                                        },
                                        {
                                                "id": "wallet-errors",
                                                "title": "wallet-errors",
                                                "translate": "NAV.BUSINESS_UNIT_MANAGER.WALLET.wallet-errors",
                                                "type": "item",
                                                "url": "/wallet/wallet-errors",
                                                "icon": "error",
                                                "priority": 1000,
                                                "roles": [
                                                        "SYSADMIN_"
                                                ]
                                        }
                                ],
                                "priority": 2000
                        }
                ],
                "priority": 200
        },
        {
                "id": "SYSTEM",
                "title": "SYSTEM",
                "translate": "NAV.SYSTEM.self",
                "type": "group",
                "icon": "location_searching",
                "children": [
                        {
                                "id": "cronjob",
                                "title": "cronjob",
                                "translate": "NAV.SYSTEM.cronjob",
                                "type": "item",
                                "url": "/cronjob",
                                "icon": "speaker_phone",
                                "priority": 100000,
                                "roles": [
                                        "SYSADMIN"
                                ]
                        }
                ],
                "priority": 100
        }
];
    }
}
